[project]
name = "mcp-server-azure-impact-reporting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.12.0",
    "httpx>=0.24.0",
    "mcp[cli]>=0.0.17",
]
